services:
  akita:
    container_name: akita-extension-backend
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  akita-db:
    container_name: akita-extension-db
    image: mongo:6.0.1
    ports:
      - ":27017"
    volumes:
      - akita-mongo-data:/data/db
  demo-server:
    container_name: akita-extension-demo-server
    image: wiremock/wiremock:2.32.0-alpine
    ports:
      - ":8080"
    command:
      - --verbose
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  akita-mongo-data:
